require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CoWorkingSpace' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  
  # React Native Maps dependencies
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  pod 'react-native-simple-crypto', :path => '../node_modules/react-native-simple-crypto'

  target 'CoWorkingSpaceTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'CoWorkingSpace-tvOS' do
  # Pods for CoWorkingSpace-tvOS

  target 'CoWorkingSpace-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
